version: '3.7'

services:
  dash_app:
    build: ./container_way/view_point
    command: python dash_main.py
    volumes:
      - ./:/dash_app/
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file:
      - ./container_way/.env
    environment:
      - REDIS_HOST=redis
  generator_app:
    build: ./container_way/generator
    command: python data_handler.py
    volumes:
      - ./:/generator_app/
    depends_on:
      - redis
    env_file:
      - ./container_way/.env
    environment:
      - REDIS_HOST=redis
  redis:
    image: "redis:6.0.6-alpine3.12"